public static PieceConfig DefaultPieceConfig()
{
    return new PieceConfig(
        Id: 0,
        Type: false,
        Projectile: "DanmaFish",
        ShootType: 0,
        ParentPiece: 0,
        AddParentAngle: false,
        LastWave: true,
        LaserLastWave: 0,
        FollowPiece: 0,
        ShootEnd: 0,
        HitAmount: 1,
        HitInterval: 6,
        ZeroHitNotDie: false,
        Scale: new float[][] { },
        Color: new int[][] { new int[] { 3 } },
        RootType: 0,
        X: new float[][] { },
        Y: new float[][] { },
        Radius: new float[][] { },
        RadiusA: new float[][] { },
        Aim: 0,
        StartTime: 0,
        Group: 1,
        GInterval: 6,
        Way: new int[][] { new int[] { 1 } },
        GAngle: new float[][] { new float[] { 0 } },
        Range: new float[][] { new float[] { 0 } },
        Life: new int[][] { },
        StartSpeed: new float[][] { new float[] { 0 } },
        StartAcc: new float[][] { },
        StartAccAngle: new float[][] { },
        EvStart: new int[][][] { },
        EvDuration: new int[][][] { },
        EvNumber: new float[][][] { },
        EvType: new int[][] { },
        VanishV3: new Vector3(0.08f, 0.08f, 0.08f),
        LaunchSfx: "",
        HitBodySfx: "",
        HitAnimationSpeed: 1f
    );
}